### PR TITLE
Support up to Instagram v10.27.

### PR DESCRIPTION
**Pull request by caio-pinho**

### CODE REVIEW

**Comment by adonisasia** [comment]
can't work on iphone5s,6,6s+,7+

**Comment by caio-pinho** [comment]
Check my fork, it is working there.

**Comment by insanj** [comment]
If this is confirmed working I'll merge and send out to BigBoss!

**Comment by adonisasia** [comment]
Thank you guys! I waiting for

**Comment by insanj** [comment]
Thanks so much, #23 has been merged, check if this works too!

**Pull request closed without merging**
